name: stockchef
description: "Gerenciamento de Estoque."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts:
  animate_do:
  smooth_page_indicator:
  flutter_riverpod:
  shared_preferences:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  flutter_stripe:
  flutter_stripe_web:
  http:
  flutter_launcher_icons:
  flutter_native_splash:


flutter_native_splash:

  color: "#F1F1FF"
  image: "assets/icon.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#EEEFF5"
  adaptive_icon_foreground: "assets/icon_android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/